name: Task 5a - Grype scan result as artifact

on:
  push:

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom.json

      - name: Run Grype scan and save result to file
        uses: anchore/scan-action@v3
        with:
          sbom: sbom.json
          fail-build: false
          output-format: json
          output-file: grype-report.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-task5a
          path: sbom.json

      - name: Upload Grype report artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: grype-report.json